@startuml
package org.liquidengine.legui{
    package component{
        abstract class Component
        abstract class Controller {
            -Tooltip tooltip
        }
        abstract class Container<T extends Component> {
            ~List<T> components
        }
        class Panel<T>
        class Widget<T>
        class Button
        class Image
        class Label
        class Tooltip
        class Layer<T> {
            ~LayerContainer<T> container
        }
        class Frame {
            ~Layer<Component> componentLayer
            ~List<Layer> layers
            ~Layer<Tooltip> tooltipLayer
        }


        Container       <--     Panel
        Container       <--     Widget
        Container       <--     Layer

        Component       <--     Tooltip
        Component       <--     Controller

        Controller      <--     Container
        Controller      <--     Button
        Controller      <--     Image
        Controller      <--     Label

        Tooltip        -*      Controller
        Layer          --*     Frame
    }

    package border{

    }

    package system{

    }

    border .. system
}
@enduml