package org.liquidengine.legui.component.event.checkbox;

import org.liquidengine.legui.component.CheckBox;
import org.liquidengine.legui.component.Frame;
import org.liquidengine.legui.event.Event;
import org.liquidengine.legui.system.context.Context;

/**
 * Event generated by default event listeners which shows that checkbox value was changed.
 */
public class CheckBoxChangeValueEvent<T extends CheckBox> extends Event<T> {

    private final boolean oldValue;
    private final boolean newValue;

    public CheckBoxChangeValueEvent(T component, Context context, Frame frame, boolean oldValue, boolean newValue) {
        super(component, context, frame);
        this.oldValue = oldValue;
        this.newValue = newValue;
    }

    /**
     * Returns old value.
     *
     * @return old value.
     */
    public boolean isOldValue() {
        return oldValue;
    }

    /**
     * Returns new value.
     *
     * @return new value.
     */
    public boolean isNewValue() {
        return newValue;
    }
}
