name: Build and check PR

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build PR for LEGUI
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v4

      # PREPARE AND BUILD
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test
